#title: AVERtek # your name photo (or website title) here
logo1: "images/AvePalmDesert Logo 1.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#F26531;"><p style="text-align:center;"><b>the PLACE, the LIFE, the LEISURE, the STYLE</h1></b></p>
  <br><br> https://alexanbahay.com/gallery/apartment-tours/
  <h2 style="text-align: center;" markdown="1"><b>SEE FOR YOURSELF</b><a href="https://www.avenidapalmdesert.com/" onclick="getOutboundLink('https://www.avenidapalmdesert.com/'); return false;"<b> HERE</b><h/2></a>
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-000000000-0 
